export type Livre = {
  id: number,
  isbn: string,
  titre: string,
  resume: string,
  imageCouverture: string,
  nbPage: number|null,
  auteurId: number|null,
  auteurNom: string,
  auteurPrenom: string,
  categorieId: number|null,
  categorieLibelle: string,
  nbExemplaire: number,
  nbExemplaireDispo: number,
  note: number,
  dateParution: string,
}
