spring.application.name=bookhub

# spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT Configuration
jwt.expiration=86400000
jwt.secret=mySecretKeyForBookhubApplicationThatIsLongEnoughForHS256Algorithm

# Database
dbname=bookhub
spring.datasource.url=jdbc:sqlserver://localhost;database=${dbname};integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

# Affiche les valeurs des paramètres (les "?" dans la requête)
logging.level.org.hibernate.orm.jdbc.bind=trace
# Formate le SQL pour qu'il soit lisible (sur plusieurs lignes)
spring.jpa.properties.hibernate.format_sql=true
# Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true


# FileSystem
spring.servlet.multipart.max-file-size=2048KB
spring.servlet.multipart.max-request-size=2048KB

springdoc.api-docs.path=/api/docs

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:migrations/schema.sql
spring.sql.init.data-locations=classpath:migrations/data.sql

logging.level.root=INFO
logging.level.fr.eni.bookhub=DEBUG
logging.level.org.springframework.data=DEBUG
# logging.file.name=logs/bookhub.log
# logging.logback.rollingpolicy.max-file-size=10MB
# logging.logback.rollingpolicy.max-history=7